language: node_js
node_js:
  - 10.18.0

services:
  - postgresql

before_script:
  - yarn install
  - psql -c 'create database grocery_shop_test;' -U postgres

script:
  - yarn test

after_success:
  - npx codecov
